### Preprocessing for the data in hma. including the data of glaciers, rivers and lakes.

In [16]:
import os
import warnings
warnings.filterwarnings('ignore')
import geopandas as gpd
import pandas as pd
import numpy as np

### 1. Preprocessing for the glacier data.

In [17]:
path_rgi60_13 = 'glaciers/rgi60_13.gpkg'   ## Cental Asia
path_rgi60_14 = 'glaciers/rgi60_14.gpkg'   ## South Asia (West)
path_rgi60_15 = 'glaciers/rgi60_15.gpkg'   ## South Asia (East)
path_rgi60_hma_lager10 = 'glaciers/rgi60_hma_lager10.gpkg'

In [18]:
## Read data
rgi60_13 = gpd.read_file(path_rgi60_13)
rgi60_14 = gpd.read_file(path_rgi60_14)
rgi60_15 = gpd.read_file(path_rgi60_15)
rgi60_13.head()

,RGIId,GLIMSId,BgnDate,EndDate,CenLon,CenLat,O1Region,O2Region,Area,Zmin,...,Aspect,Lmax,Status,Connect,Form,TermType,Surging,Linkages,Name,geometry
0,RGI60-13.00001,G079494E34471N,20000810,-9999999,79.4939,34.4713,13,5,0.432,5678,...,312,683,0,0,0,0,9,9,None,"MULTIPOLYGON (((79.49945 34.47555, 79.49880 34..."
1,RGI60-13.00002,G077951E35545N,20020802,-9999999,77.9513,35.5452,13,5,0.367,5889,...,195,1307,0,0,0,0,9,9,None,"MULTIPOLYGON (((77.95519 35.55007, 77.95517 35..."
2,RGI60-13.00003,G077930E35519N,20020802,-9999999,77.9295,35.5188,13,5,0.070,5646,...,318,426,0,0,0,0,9,9,None,"MULTIPOLYGON (((77.92863 35.52057, 77.92864 35..."
3,RGI60-13.00004,G077924E35525N,20020802,-9999999,77.9237,35.5252,13,5,0.255,5698,...,39,605,0,0,0,0,9,9,None,"MULTIPOLYGON (((77.91713 35.52720, 77.91764 35..."
4,RGI60-13.00005,G077914E35531N,20020802,-9999999,77.9141,35.5309,13,5,0.261,5644,...,8,389,0,0,0,0,9,9,None,"MULTIPOLYGON (((77.91939 35.52980, 77.91938 35..."

In [19]:
print('Number of the glaciers:')
print('rgi60_13:', rgi60_13.shape[0], '\nrgi60_14:', rgi60_14.shape[0], '\nrgi60_15:',rgi60_15.shape[0]); 
print('Area of the glaciers:')
print('rgi60_13: %.3f km2' % rgi60_13.Area.sum(), '\nrgi60_14: %.3f km2' % rgi60_14.Area.sum(), '\nrgi60_15: %.3f km2' % rgi60_15.Area.sum())

Number of the glaciers:
rgi60_13: 54429
rgi60_14: 27988
rgi60_15: 13119
Area of the glaciers:
rgi60_13: 49303.415 km2
rgi60_14: 33568.298 km2
rgi60_15: 14734.204 km2

In [20]:
### Select the glaciers which area larger than 10 km2
rgi60_13_sel = rgi60_13.loc[rgi60_13['Area'] > 10]
rgi60_14_sel = rgi60_14.loc[rgi60_14['Area'] > 10]
rgi60_15_sel = rgi60_15.loc[rgi60_15['Area'] > 10]
rgi60_hma_lager10 = pd.concat([rgi60_13_sel , rgi60_14_sel, rgi60_15_sel])
print(rgi60_hma_lager10.shape)
rgi60_hma_lager10.head()

(1221, 23)

,RGIId,GLIMSId,BgnDate,EndDate,CenLon,CenLat,O1Region,O2Region,Area,Zmin,...,Aspect,Lmax,Status,Connect,Form,TermType,Surging,Linkages,Name,geometry
174,RGI60-13.00175,G078451E34955N,20020802,-9999999,78.450700,34.954600,13,5,14.779,5572,...,99,6199,0,0,0,0,9,9,None,"MULTIPOLYGON (((78.43065 34.97947, 78.43064 34..."
642,RGI60-13.00643,G094928E30607N,19990923,-9999999,94.928018,30.607432,13,9,28.533,4345,...,46,10791,0,0,0,0,9,9,None,"MULTIPOLYGON (((94.97412 30.60416, 94.97372 30..."
760,RGI60-13.00761,G094637E30633N,19990923,-9999999,94.636865,30.632809,13,9,36.251,4185,...,23,13883,0,0,0,0,9,9,None,"MULTIPOLYGON (((94.57537 30.65285, 94.57536 30..."
787,RGI60-13.00788,G094383E30581N,19990923,-9999999,94.383484,30.581293,13,9,34.120,4116,...,30,13052,0,0,0,0,9,9,None,"MULTIPOLYGON (((94.43347 30.58483, 94.43378 30..."
963,RGI60-13.00964,G094708E30413N,19990923,-9999999,94.708196,30.413226,13,9,24.445,2687,...,162,13267,0,0,0,0,9,9,None,"MULTIPOLYGON (((94.71151 30.44324, 94.71223 30..."

In [21]:
# ### Write out
# rgi60_hma_lager10.to_file(path_rgi60_hma_lager10, driver='GPKG')

### 2. Preprocessing for the river data
Extract hma rivers from global rivers.

In [34]:
path_rivers_global = 'rivers/major_rivers_global.gpkg'
path_rivers_hma = 'rivers/rivers_hma.gpkg'

### Note:   
-- Yarlung Zangbo also know as Brahmaputra;   
-- Nu Jiang also know as Salween;   
-- Chang Jiang also know as Yangtze River.

In [33]:
### Check data
rivers_global = gpd.read_file(path_rivers_global)
print(rivers_global.shape)
rivers_global.head()

(98, 5)

,NAME,SYSTEM,MILES,KILOMETERS,geometry
0,Kolyma,None,2551.51838,4106.27900,"MULTILINESTRING ((144.84189 61.75915, 144.8257..."
1,Parana,Parana,1616.20622,2601.03698,"MULTILINESTRING ((-51.00640 -20.07941, -51.029..."
2,San Francisco,None,1493.57095,2403.67425,"MULTILINESTRING ((-46.43639 -20.25807, -46.498..."
3,Japura,Amazon,1222.80771,1967.92219,"MULTILINESTRING ((-76.71056 1.62417, -76.70029..."
4,Putumayo,Amazon,889.91926,1432.18908,"MULTILINESTRING ((-76.86806 1.30055, -76.86695..."

In [32]:
### Rivers in hma
rivers_hma = ['Indus', 'Ganges', 'Yarlung Zangbo', 'Mekong', 'Irrawaddy', 'Huang He', \
              'Syr Darya', 'Amu Darya', 'Chang Jiang', 'Xi Jiang', 'Nu Jiang']
ids = [int(np.where(rivers_global.NAME==name)[0]) for name in rivers_hma]
rivers_hma = rivers_global.loc[ids]
print(rivers_hma.shape)
rivers_hma.head()

(11, 5)

,NAME,SYSTEM,MILES,KILOMETERS,geometry
57,Indus,None,2015.16218,3243.09564,"MULTILINESTRING ((67.48645 24.04542, 67.65091 ..."
56,Ganges,None,1481.59615,2384.40264,"MULTILINESTRING ((79.87328 30.95868, 79.81163 ..."
55,Yarlung Zangbo,None,1897.09807,3053.08950,"MULTILINESTRING ((82.00998 30.48415, 82.24191 ..."
62,Mekong,None,2942.45095,4735.42525,"MULTILINESTRING ((93.88553 33.26776, 93.88915 ..."
61,Irrawaddy,None,1297.67231,2088.40532,"MULTILINESTRING ((94.98852 16.23617, 95.12437 ..."

In [35]:
# ### Write out
# rivers_hma.to_file(path_rivers_hma, driver='GPKG')